# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
from machine_learning import generate_output


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1088x670")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 670,
    width = 1088,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    14.0,
    13.0,
    392.0,
    294.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    30.0,
    33.0,
    anchor="nw",
    text="Kullanılan Model: SVM",
    fill="#000000",
    font=("Inter", 20 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    203.0,
    412.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    203.0,
    600.0,
    image=image_image_2
)

canvas.create_rectangle(
    409.0,
    14.0,
    1074.0,
    648.0,
    fill="#D9D9D9",
    outline="")

button_1 = Button(
    window,
    text="Çalıştır",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: generate_output(canvas,entry_1,progressbar,true_text,false_text),
    relief="flat",
    bg="#9F9F9F",
    fg="#000000",
    font=("Inter", 16)
)
button_1.place(
    x=438.0,
    y=581.0,
    width=607.0,
    height=51.0
)

progressbar = ttk.Progressbar(
    window,
    orient='horizontal',
    mode='determinate',
    length=606
)
progressbar.place(
    x=439.0,
    y=522.0,
    width=606.0,
    height=38.0
)

canvas.create_rectangle(
    409.0,
    382.0,
    1074.9999386530944,
    385.0121027157519,
    fill="#9f9f9f",
    outline="")

true_text = canvas.create_text(
    441.0,
    413.0,
    anchor="nw",
    text="Doğru Tahmin: 0/114 | %00",
    fill="#000000",
    font=("Inter", 24 * -1)
)

false_text = canvas.create_text(
    442.0,
    467.0,
    anchor="nw",
    text="Yanlış Tahmin: 0/114 | %00",
    fill="#000000",
    font=("Inter", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    742.5,
    194.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=432.0,
    y=34.0,
    width=621.0,
    height=319.0
)

canvas.create_text(
    28.0,
    73.0,
    anchor="nw",
    text="Hasta Verisi Sayısı: 569",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    28.0,
    116.0,
    anchor="nw",
    text="İyi Huylu Sayısı: 357",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    28.0,
    159.0,
    anchor="nw",
    text="Kötü Huylu Sayısı: 212",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    28.0,
    202.0,
    anchor="nw",
    text="Eğitim Sayısı: 455",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    28.0,
    245.0,
    anchor="nw",
    text="Test Sayısı: 114",
    fill="#000000",
    font=("Inter", 20 * -1)
)



window.resizable(False, False)
window.mainloop()
